export const userColums = [
    { field: 'id', headerName: 'No', width: 90 },
    { field: 'classname', headerName: 'Client ID', width: 320 },
    { field: 'date', headerName: 'Plan', width: 350 },
    { field: 'days', headerName: 'From Date', width: 265 },
    { field: 'time', headerName: 'TO Date', width: 265 },
]

export const userRows = [
    {
        id: 1,
        classname: "Abhay Bhingradia",
        date: "No Program Assigned",
        days: "-",
        time: "-",
    },
    {
        id: 2,
        classname: "Denish Lakhani",
        date: "No Program Assigned	",
        days: "-",
        time: "-",
    },
    {
        id: 3,
        classname: "Abhinav Agarwal",
        date: "No Program Assigned",
        days: "-",
        time: "-",
    },
    {
        id: 4,
        classname: "Jeel_Patel",
        date: "No Program Assigned",
        days: "-",
        time: "-",
    },
    {
        id: 5,
        classname: "Abhinay Sharma",
        date: "No Program Assigned",
        days: "-",
        time: "-",
    },
    {
        id: 6,
        classname: "Ayush Shah",
        date: "No Program Assigned",
        days: "-",
        time: "-",
    },
    {
        id: 7,
        classname: "Dustin Porior",
        date: "No Program Assigned",
        days: "-",
        time: "-",
    },
    {
        id: 8,
        classname: "Smit Patel",
        date: "No Program Assigned",
        days: "-",
        time: "-",
    },
    {
        id: 9,
        classname: "Aditya Kabra",
        date: "No Program Assigned",
        days: "-",
        time: "-",
    },
    {
        id: 10,
        classname: "Paril Vachanni",
        date: "No Program Assigned",
        days: "-",
        time: "-",
    },
    {
        id: 11,
        classname: "CBM0000018",
        date: "No Program Assigned",
        days: "-",
        time: "-",
    },
]