export const userColums = [
    { field: 'id', headerName: 'No', width: 90 },
    { field: 'classname', headerName: 'Member ID', width: 210 },
    { field: 'date', headerName: 'User Name', width: 280 },
    { field: 'days', headerName: 'Bed Time', width: 245 },
    { field: 'time', headerName: 'Wake Up Time', width: 240 },
    { field: 'trainer', headerName: 'Hr: Min', width: 220 },
]

export const userRows = [
    {
        id: 1,
        classname: "CBM0000008",
        date: "aashish_lakhani",
        days: "12:00 AM",
        time: "7:00 AM",
        trainer: "12:0",
    },
    {
        id: 2,
        classname: "CBM0000010",
        date: "abhay_bhingradia	",
        days: "12:00 AM",
        time: "6:45 AM",
        trainer: "1:15",
    },
    {
        id: 3,
        classname: "CBM0000011",
        date: "abhinav_agarwal",
        days: "Select..",
        time: "Select..",
        trainer: "",
    },
    {
        id: 4,
        classname: "CBM0000012",
        date: "Jeel_Patel",
        days: "Select..",
        time: "Select..",
        trainer: "",
    },
    {
        id: 5,
        classname: "CBM0000013",
        date: "abhinay_sharma",
        days: "Select..",
        time: "Select..",
        trainer: "2:0",
    },
    {
        id: 6,
        classname: "CBM0000014",
        date: "abhishek_agarwal",
        days: "Select..",
        time: "Select..",
        trainer: "",
    },
    {
        id: 7,
        classname: "CBM0000694",
        date: "abhishek_dalmia",
        days: "Select..",
        time: "Select..",
        trainer: "",
    },
    {
        id: 8,
        classname: "CBM0000015",
        date: "aditya_jain",
        days: "Select..",
        time: "Select..",
        trainer: "",
    },
    {
        id: 9,
        classname: "CBM0000016",
        date: "ajay_luharuwalla",
        days: "Select..",
        time: "Select..",
        trainer: "",
    },
    {
        id: 10,
        classname: "CBM0000017",
        date: "ajay_soni",
        days: "Select..",
        time: "Select..",
        trainer: "",
    },
    {
        id: 11,
        classname: "CBM0000018",
        date: "ajay_vijay",
        days: "Select..",
        time: "Select..",
        trainer: " ",
    },
]